[package]
name = "tx_graph"
version = "0.1.0"
authors = ["Matthias Reisinger <matthias.j.reisinger@gmail.com>"]

[dependencies]
memmap = "0.6.2"
redis = "0.8.0"
byteorder = "1.2.1"
data-encoding = "2.1.1"
dotenv = "0.11.0"

[dev-dependencies]
redis_test = { path = "../redis_test" }
tempdir = "0.3"
