CREATE TABLE transactions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hash BINARY(32) NOT NULL,
    version INT UNSIGNED NOT NULL,
    lock_time INT UNSIGNED NOT NULL,
    creation_time INT UNSIGNED NOT NULL,
    block_id INT UNSIGNED NOT NULL REFERENCES blocks (id)
)
