CREATE TABLE outputs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    output_index INT UNSIGNED NOT NULL,
    value BIGINT UNSIGNED NOT NULL,
    transaction_id INT UNSIGNED NOT NULL REFERENCES transactions (id)
)
